### ISSUE TITLE
Broadcast game results

### ISSUE THREAD

**Issue by Brutus5000** [micheljung/faf-java-server#104]
Not sure about the overall requirement, but GW and/or external matchmaker services need to get the game results for the games they started. I would suggest we broadcast them to all connected clients.

**Comment by micheljung** [comment]
Then we would broadcast the game results to 1000 clients of which 999 have no interest in it.

I think it's finally time to implement a pub/sub mechanism. AFAIK, STOMP provides this out of the box. We should compare this to a manual implementation and decide from there.

**Comment by Katharsas** [comment]
Note:
Authentication and Authorization via Spring Security for plain Websocket (without STOMP) was kind of a pain to deal with for me, because i think you need to [manually intercept Websocket CONNECT messages and place user information into the Websocket session](https://stackoverflow.com/questions/49753433/how-to-use-spring-security-with-spring-websocket-support-but-without-stomp). So if you need authentication (which you probably don't need for now but maybe in the long run), using STOMP or HTTP is probably better than plain websocket.
